version: "3.7"

# PORT - service
# 8301 - backend
# 8302 - frontend

services:
  backend:
    image: mono-todo-backend
    ports:
      - 8301:8080
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
        window: 20s
    environment:
      - TIMEZONE=Europe/Warsaw

  frontend:
    image: mono-todo-frontend
    ports:
      - 8302:80
    depends_on:
      - backend
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 10s
